// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('myApp', ['ngRoute', 'myAppControllers']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/app', {
        templateUrl: 'partials/item-list.html',
        controller: 'MyAppMainCtrl'
      });
    }
  ]);

}).call(this);
