// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('myAppControllers', []).controller('MyAppMainCtrl', [
    '$scope', '$http', function($scope, $http) {
      return $http.get('stubs/stubs.json').success(function(data) {
        return $scope.items = data;
      });
    }
  ]);

}).call(this);
